---
  lmp_binary: ""
  nprocs: "4"
  args: "-cite none"
  mpiexec: "mpirun"
  mpiexec_numproc_flag: "-np"
  tolerance:
    PotEng:
      abs: 1e-4
      rel: 1e-7
    TotEng:
      abs: 1e-4
      rel: 1e-7
    Press:
      abs: 1e-4
      rel: 1e-7
    Temp:
      abs: 1e-4
      rel: 1e-7
    E_vdwl:
      abs: 1e-3
      rel: 1e-7
  nugget: 1.0
  epsilon: 1e-16
